
RPI_GPIO_SENSOR1_PIN = 25
RPI_GPIO_SENSOR2_PIN = 23

SENSOR_DIST = 0.3 #Meters
DIST_CAMERA_PINS = 2.0 #Meters

CAPTURE_IMPACT_DURATION = 1.0 #Seconds
CAPTURE_AFTER_IMPACT_TIMEOUT = 2.0 #seconds
CAMERA_RESOLUTION = (640,480)
CAMERA_SHUTTER_SPEED = 10000
